#![forbid(unsafe_code)]
#![warn(rust_2024_compatibility, missing_docs, missing_debug_implementations)]
#![allow(clippy::module_name_repetitions)]
#![allow(clippy::must_use_candidate)]
#![allow(clippy::missing_errors_doc)]
// Scaffold assembly functions are deterministic template builders; the repo limit remains 150
// lines.
#![allow(clippy::too_many_lines)]
// Scaffold writes are synchronous CLI/facade operations, not async request handlers.
#![allow(clippy::disallowed_methods)]

//! Init, template, skills, and project scaffolding services.

use std::{collections::BTreeMap, fmt::Write as _, fs, path::Path};

use camino::Utf8PathBuf;
use minijinja::Environment;
use repoctl_core::{
    Diagnostic, FileOperation, IacProvider, InitPlan, InitRequest, NewProjectRequest, OwnerHandle,
    ProjectKind, RenderPlan, RenderRequest, RenderedTemplate, RepoRelativePath, RepoRoot,
    RepoctlError, ResolvedTemplateSource, SkillsFacadeReport, SkillsFacadeRequest, TemplateEngine,
    TemplateListReport, TemplateListRequest, TemplateRenderRequest, TemplateSource,
    TemplateSourceResolver, TemplateSummary, YamlManifestParser, utf8_path_buf,
};
use serde_json::json;

const MANAGED_HEADER: &str = "# @generated by repoctl";
const BLOCK_BEGIN: &str = "<!-- repoctl:begin -->";
const BLOCK_END: &str = "<!-- repoctl:end -->";
/// Service for init, skills, and project scaffolding.
#[derive(Clone, Debug, Default)]
pub struct ScaffoldService;

impl ScaffoldService {
    /// Creates a scaffold service with built-in adapters.
    pub fn with_default_adapters() -> Self {
        Self
    }

    /// Plans and optionally applies repository initialization.
    pub fn init(&self, request: &InitRequest) -> Result<InitPlan, RepoctlError> {
        if request.layout != repoctl_core::RepoLayout::Functional {
            return Err(RepoctlError::diagnostic(Diagnostic::error(
                "init.layout.unsupported",
                "repoctl v0.2 only supports the functional layout",
            )));
        }
        let root = root_path(&request.repo_root)?;
        let mut operations = Vec::new();
        for directory in [
            ".repoctl",
            ".agent/skills",
            ".claude/skills",
            ".github/workflows",
            "protos",
            "apps",
            "foundations",
            "frameworks",
            "core-infra",
            "templates",
            "tools",
            "docs",
            "target/repoctl",
        ] {
            operations.push(directory_operation(directory)?);
        }
        operations.push(file_operation(
            "repo.yaml",
            repo_manifest(&request.name.to_string()),
        )?);
        operations.push(file_operation(
            "AGENTS.md",
            root_agents(&request.name.to_string()),
        )?);
        operations.push(file_operation("docs/index.md", docs_index())?);
        operations.extend(skill_operations()?);
        apply_operations(&root, &operations, request.dry_run)?;
        Ok(InitPlan {
            operations,
            warnings: Vec::new(),
            next_steps: vec![
                "Commit the initialized structure.".to_string(),
                "Create your first app with repoctl new app apps/<name>.".to_string(),
                "Run repoctl graph validate.".to_string(),
            ],
        })
    }

    /// Checks or syncs generated skills.
    pub fn skills(
        &self,
        request: &SkillsFacadeRequest,
    ) -> Result<SkillsFacadeReport, RepoctlError> {
        let root = locate_or_current(request.repo.as_deref())?;
        let operations = skill_operations()?;
        let mut diagnostics = Vec::new();
        for operation in &operations {
            let absolute = root.join(operation.path.as_str());
            match (&operation.content, absolute.exists()) {
                (Some(expected), true) => {
                    let current = fs::read_to_string(absolute.as_std_path())
                        .map_err(|source| RepoctlError::io(absolute.clone(), source))?;
                    if current != *expected {
                        diagnostics.push(
                            Diagnostic::error(
                                "skills.out_of_sync",
                                format!("skill `{}` is out of sync", operation.path),
                            )
                            .with_path(operation.path.as_str()),
                        );
                    }
                }
                (Some(_), false) => diagnostics.push(
                    Diagnostic::error(
                        "skills.missing",
                        format!("skill `{}` is missing", operation.path),
                    )
                    .with_path(operation.path.as_str()),
                ),
                (None, _) => {}
            }
        }
        if request.sync && !request.dry_run {
            apply_operations(&root, &operations, false)?;
            diagnostics.clear();
        }
        Ok(SkillsFacadeReport { diagnostics })
    }

    /// Plans and optionally applies a new project scaffold.
    pub fn new_project(&self, request: &NewProjectRequest) -> Result<RenderPlan, RepoctlError> {
        let root = locate_or_current(request.repo.as_deref())?;
        let operations = match request.kind {
            ProjectKind::App => Self::app_operations(request)?,
            ProjectKind::Framework => Self::framework_operations(request)?,
            ProjectKind::FoundationService => Self::foundation_operations(request)?,
            ProjectKind::ProtoRoot | ProjectKind::CoreInfra => {
                return Err(RepoctlError::diagnostic(Diagnostic::error(
                    "new.kind.unsupported",
                    "new project supports app, framework, and foundation-service",
                )));
            }
        };
        let diagnostics = apply_operations(&root, &operations, request.dry_run)?;
        Ok(RenderPlan {
            operations,
            diagnostics,
        })
    }

    /// Lists built-in and repository-local templates.
    pub fn list_templates(
        &self,
        request: &TemplateListRequest,
    ) -> Result<TemplateListReport, RepoctlError> {
        let root = locate_or_current(request.repo.as_deref())?;
        let repo_root = RepoRoot {
            absolute: root.clone(),
        };
        let source_resolver = DefaultTemplateSourceResolver::default();
        let mut templates = Vec::new();
        for name in builtin_template_names() {
            let template_data = source_resolver.resolve(
                &repo_root,
                &TemplateSource::Builtin {
                    name: name.to_string(),
                },
            )?;
            templates.push(TemplateSummary {
                source: format!("builtin:{name}"),
                name: template_data.manifest.name,
                kind: template_data.manifest.kind,
            });
        }
        let local_root = root.join("templates");
        if local_root.is_dir() {
            for entry in fs::read_dir(local_root.as_std_path())
                .map_err(|source| RepoctlError::io(local_root.clone(), source))?
            {
                let entry = entry.map_err(|source| RepoctlError::io(local_root.clone(), source))?;
                if !entry
                    .file_type()
                    .map_err(|source| RepoctlError::io(local_root.clone(), source))?
                    .is_dir()
                {
                    continue;
                }
                let name = entry.file_name().to_string_lossy().to_string();
                let source_root = RepoRelativePath::new(format!("templates/{name}"))
                    .map_err(RepoctlError::diagnostic)?;
                let template_data = source_resolver.resolve(
                    &repo_root,
                    &TemplateSource::Local {
                        root: source_root.clone(),
                    },
                );
                if let Ok(template_data) = template_data {
                    templates.push(TemplateSummary {
                        source: format!("local:{source_root}"),
                        name: template_data.manifest.name,
                        kind: template_data.manifest.kind,
                    });
                }
            }
        }
        templates.sort_by(|left, right| left.source.cmp(&right.source));
        Ok(TemplateListReport {
            templates,
            diagnostics: Vec::new(),
        })
    }

    /// Renders a built-in or local template into a plan-first file operation set.
    pub fn render_template(
        &self,
        request: &TemplateRenderRequest,
    ) -> Result<RenderPlan, RepoctlError> {
        let root = locate_or_current(request.repo.as_deref())?;
        let repo_root = RepoRoot {
            absolute: root.clone(),
        };
        let source_resolver = DefaultTemplateSourceResolver::default();
        let engine = MiniJinjaTemplateEngine;
        let template_data = source_resolver.resolve(&repo_root, &request.source)?;
        let mut operations = Vec::new();
        for file in &template_data.manifest.files {
            if !should_render(file.when.as_deref(), &request.inputs, &engine)? {
                continue;
            }
            let target = engine.render(&RenderRequest {
                template: template_data.manifest.clone(),
                file: file.clone(),
                context: request.inputs.clone(),
            })?;
            let target = String::from_utf8(target.bytes).map_err(|source| {
                RepoctlError::diagnostic(Diagnostic::error(
                    "template.target.invalid_utf8",
                    format!("template target did not render as UTF-8: {source}"),
                ))
            })?;
            let path = RepoRelativePath::new(target).map_err(RepoctlError::diagnostic)?;
            let source = template_source_content(&root, &request.source, &template_data, file)?;
            let existing = {
                let absolute = root.join(path.as_str());
                if absolute.is_file() {
                    Some(
                        fs::read_to_string(absolute.as_std_path())
                            .map_err(|source| RepoctlError::io(absolute, source))?,
                    )
                } else {
                    None
                }
            };
            let content =
                engine.render_content(file, &source, existing.as_deref(), &request.inputs)?;
            operations.push(FileOperation {
                path,
                operation: file.mode.clone(),
                content: Some(content),
            });
        }
        let diagnostics = apply_operations(&root, &operations, request.dry_run)?;
        Ok(RenderPlan {
            operations,
            diagnostics,
        })
    }

    fn app_operations(request: &NewProjectRequest) -> Result<Vec<FileOperation>, RepoctlError> {
        let slug = slug_from_path(&request.path)?;
        let project = project_name(&request.path, &ProjectKind::App)?;
        let owner = owner_or_default(request.owner.as_ref(), &slug);
        let mut workspaces = Vec::new();
        let mut tasks: BTreeMap<&str, Vec<String>> = BTreeMap::new();
        let stack = if request.stack.is_empty() {
            vec!["rust-api".to_string()]
        } else {
            request.stack.clone()
        };
        if stack.iter().any(|entry| entry == "rust-api") {
            workspaces.push(
                r#"  - name: api
    language: rust
    root: api
    manifest: api/Cargo.toml
    lockfile: api/Cargo.lock
    target_dir: "{repo_root}/target/rust""#
                    .to_string(),
            );
            push_task(&mut tasks, "check", "api", "cargo check --workspace");
            push_task(&mut tasks, "test", "api", "cargo test --workspace");
            push_task(
                &mut tasks,
                "build",
                "api",
                "cargo build --workspace --release",
            );
        }
        if stack.iter().any(|entry| entry == "bun-web") {
            workspaces.push(
                r#"  - name: web
    language: typescript
    toolchain: bun
    root: web
    manifest: web/package.json
    lockfile: web/bun.lock
    cache_dir: "{repo_root}/target/bun""#
                    .to_string(),
            );
            push_task(&mut tasks, "check", "web", "bun run check");
            push_task(&mut tasks, "test", "web", "bun test");
            push_task(&mut tasks, "build", "web", "bun run build");
        }
        if stack.iter().any(|entry| entry == "uv-jobs") {
            workspaces.push(
                r#"  - name: jobs
    language: python
    toolchain: uv
    root: jobs
    manifest: jobs/pyproject.toml
    lockfile: jobs/uv.lock
    cache_dir: "{repo_root}/target/uv""#
                    .to_string(),
            );
            push_task(&mut tasks, "check", "jobs", "uv run ruff check .");
            push_task(&mut tasks, "test", "jobs", "uv run pytest");
        }
        let mut manifest = format!(
            r#"{MANAGED_HEADER}
schema: company.project/v1
name: {project}
kind: app
path: {path}
owners:
  - "{owner}"
visibility: internal

workspaces:
{workspaces}

tasks:
{tasks}
"#,
            path = request.path,
            workspaces = workspaces.join("\n"),
            tasks = render_tasks(&tasks),
        );
        if let Some(provider) = &request.iac {
            write!(
                manifest,
                r"
iac:
  root: iac
  provider: {}
  stacks:
    - dev
    - staging
    - prod
",
                iac_provider_name(provider)
            )
            .map_err(|error| {
                RepoctlError::Internal(format!("failed to render iac block: {error}"))
            })?;
        }
        manifest.push_str(
            r#"
deploy:
  root: deploy
  environments:
    - dev
    - staging
    - prod

ai:
  editable:
    - api/**
    - web/src/**
    - jobs/**
    - iac/**
    - deploy/**
    - docs/**
  do_not_edit:
    - "**/generated/**"
    - deploy/prod/**
    - iac/stacks/prod/**
  docs:
    - README.md
"#,
        );
        let mut operations = project_base_operations(request, &slug, manifest)?;
        if stack.iter().any(|entry| entry == "rust-api") {
            operations.push(file_operation(
                &format!("{}/api/Cargo.toml", request.path),
                rust_workspace_toml(&slug),
            )?);
            operations.push(file_operation(
                &format!("{}/api/src/lib.rs", request.path),
                "//! App API crate.\n".to_string(),
            )?);
        }
        if stack.iter().any(|entry| entry == "bun-web") {
            operations.push(file_operation(
                &format!("{}/web/package.json", request.path),
                package_json(&slug),
            )?);
            operations.push(file_operation(
                &format!("{}/web/src/main.tsx", request.path),
                "export const appName = \"repoctl-app\";\n".to_string(),
            )?);
        }
        if stack.iter().any(|entry| entry == "uv-jobs") {
            operations.push(file_operation(
                &format!("{}/jobs/pyproject.toml", request.path),
                pyproject_toml(&slug),
            )?);
            operations.push(file_operation(
                &format!("{}/jobs/src/main.py", request.path),
                "def main() -> None:\n    return None\n".to_string(),
            )?);
        }
        if request.iac.is_some() {
            operations.push(file_operation(
                &format!("{}/iac/Pulumi.yaml", request.path),
                format!("{MANAGED_HEADER}\nname: {slug}\nruntime: yaml\n"),
            )?);
            operations.push(file_operation(
                &format!("{}/iac/stacks/prod.yaml", request.path),
                format!("{MANAGED_HEADER}\nconfig: {{}}\n"),
            )?);
        }
        Ok(operations)
    }

    fn framework_operations(
        request: &NewProjectRequest,
    ) -> Result<Vec<FileOperation>, RepoctlError> {
        let slug = slug_from_path(&request.path)?;
        let project = project_name(&request.path, &ProjectKind::Framework)?;
        let owner = owner_or_default(request.owner.as_ref(), "platform");
        let languages = if request.languages.is_empty() {
            vec!["rust".to_string()]
        } else {
            request.languages.clone()
        };
        let mut workspaces = Vec::new();
        let mut public_facades = String::new();
        let mut internal = String::new();
        let mut tasks: BTreeMap<&str, Vec<String>> = BTreeMap::new();
        if languages.iter().any(|language| language == "rust") {
            workspaces.push(
                r#"  - name: rust
    language: rust
    root: rust
    manifest: rust/Cargo.toml
    lockfile: rust/Cargo.lock
    target_dir: "{repo_root}/target/rust""#
                    .to_string(),
            );
            writeln!(public_facades, "  rust:\n    - rust/crates/{slug}-facade").map_err(
                |error| RepoctlError::Internal(format!("failed to render facade map: {error}")),
            )?;
            writeln!(internal, "  rust:\n    - rust/crates/{slug}-internal").map_err(|error| {
                RepoctlError::Internal(format!("failed to render internal map: {error}"))
            })?;
            push_task(&mut tasks, "check", "rust", "cargo check --workspace");
            push_task(&mut tasks, "test", "rust", "cargo test --workspace");
        }
        if languages.iter().any(|language| language == "typescript") {
            workspaces.push(
                r#"  - name: ts
    language: typescript
    toolchain: bun
    root: ts
    manifest: ts/package.json
    lockfile: ts/bun.lock
    cache_dir: "{repo_root}/target/bun""#
                    .to_string(),
            );
            writeln!(public_facades, "  typescript:\n    - ts/packages/{slug}").map_err(
                |error| RepoctlError::Internal(format!("failed to render facade map: {error}")),
            )?;
            writeln!(internal, "  typescript:\n    - ts/packages/{slug}-internal").map_err(
                |error| RepoctlError::Internal(format!("failed to render internal map: {error}")),
            )?;
            push_task(&mut tasks, "check", "ts", "bun run check");
            push_task(&mut tasks, "test", "ts", "bun test");
        }
        let manifest = format!(
            r#"{MANAGED_HEADER}
schema: company.project/v1
name: {project}
kind: framework
path: {path}
owners:
  - "{owner}"

workspaces:
{workspaces}

public_facades:
{public_facades}
internal:
{internal}
tasks:
{tasks}

policies:
  allow_app_dependency_on_facade_only: true
"#,
            path = request.path,
            workspaces = workspaces.join("\n"),
            tasks = render_tasks(&tasks),
        );
        let mut operations = project_base_operations(request, &slug, manifest)?;
        if languages.iter().any(|language| language == "rust") {
            operations.push(file_operation(
                &format!("{}/rust/Cargo.toml", request.path),
                rust_workspace_manifest_toml(&[
                    format!("crates/{slug}-facade"),
                    format!("crates/{slug}-internal"),
                ]),
            )?);
            operations.push(file_operation(
                &format!("{}/rust/crates/{slug}-facade/Cargo.toml", request.path),
                rust_workspace_toml(&format!("{slug}-facade")),
            )?);
            operations.push(file_operation(
                &format!("{}/rust/crates/{slug}-internal/Cargo.toml", request.path),
                rust_workspace_toml(&format!("{slug}-internal")),
            )?);
            operations.push(file_operation(
                &format!("{}/rust/crates/{slug}-facade/src/lib.rs", request.path),
                "//! Public facade crate.\n".to_string(),
            )?);
            operations.push(file_operation(
                &format!("{}/rust/crates/{slug}-internal/src/lib.rs", request.path),
                "//! Internal crate.\n".to_string(),
            )?);
        }
        if languages.iter().any(|language| language == "typescript") {
            operations.push(file_operation(
                &format!("{}/ts/package.json", request.path),
                package_json(&slug),
            )?);
        }
        Ok(operations)
    }

    fn foundation_operations(
        request: &NewProjectRequest,
    ) -> Result<Vec<FileOperation>, RepoctlError> {
        let slug = slug_from_path(&request.path)?;
        let project = project_name(&request.path, &ProjectKind::FoundationService)?;
        let owner = owner_or_default(request.owner.as_ref(), &slug);
        let clients = if request.clients.is_empty() {
            vec!["rust".to_string()]
        } else {
            request.clients.clone()
        };
        let mut workspaces = vec![
            r#"  - name: service
    language: rust
    root: service
    manifest: service/Cargo.toml
    lockfile: service/Cargo.lock
    target_dir: "{repo_root}/target/rust""#
                .to_string(),
        ];
        let mut public_clients = String::new();
        if clients.iter().any(|client| client == "rust") {
            writeln!(
                public_clients,
                "  rust:\n    - clients/rust/crates/{slug}-client"
            )
            .map_err(|error| {
                RepoctlError::Internal(format!("failed to render client map: {error}"))
            })?;
            workspaces.push(
                r#"  - name: clients-rust
    language: rust
    root: clients/rust
    manifest: clients/rust/Cargo.toml
    lockfile: clients/rust/Cargo.lock
    target_dir: "{repo_root}/target/rust""#
                    .to_string(),
            );
        }
        if clients.iter().any(|client| client == "typescript") {
            writeln!(
                public_clients,
                "  typescript:\n    - clients/ts/packages/{slug}-client"
            )
            .map_err(|error| {
                RepoctlError::Internal(format!("failed to render client map: {error}"))
            })?;
            workspaces.push(
                r#"  - name: clients-ts
    language: typescript
    toolchain: bun
    root: clients/ts
    manifest: clients/ts/package.json
    lockfile: clients/ts/bun.lock
    cache_dir: "{repo_root}/target/bun""#
                    .to_string(),
            );
        }
        if clients.iter().any(|client| client == "python") {
            writeln!(
                public_clients,
                "  python:\n    - clients/python/packages/{slug}-client"
            )
            .map_err(|error| {
                RepoctlError::Internal(format!("failed to render client map: {error}"))
            })?;
            workspaces.push(
                r#"  - name: clients-python
    language: python
    toolchain: uv
    root: clients/python
    manifest: clients/python/pyproject.toml
    lockfile: clients/python/uv.lock
    cache_dir: "{repo_root}/target/uv""#
                    .to_string(),
            );
        }
        let mut tasks = BTreeMap::new();
        push_task(&mut tasks, "check", "service", "cargo check --workspace");
        push_task(&mut tasks, "test", "service", "cargo test --workspace");
        let mut manifest = format!(
            r#"{MANAGED_HEADER}
schema: company.project/v1
name: {project}
kind: foundation-service
path: {path}
owners:
  - "{owner}"

workspaces:
{workspaces}

public_clients:
{public_clients}
tasks:
{tasks}
"#,
            path = request.path,
            workspaces = workspaces.join("\n"),
            tasks = render_tasks(&tasks),
        );
        if let Some(proto) = &request.proto {
            write!(
                manifest,
                r"
protos:
  owns:
    - protos/{proto_path}/**
",
                proto_path = proto.as_str().replace('.', "/")
            )
            .map_err(|error| {
                RepoctlError::Internal(format!("failed to render proto block: {error}"))
            })?;
        }
        if let Some(provider) = &request.iac {
            write!(
                manifest,
                r"
iac:
  root: iac
  provider: {}
  stacks:
    - dev
    - staging
    - prod
",
                iac_provider_name(provider)
            )
            .map_err(|error| {
                RepoctlError::Internal(format!("failed to render iac block: {error}"))
            })?;
        }
        manifest.push_str("\ndeploy:\n  root: deploy\n");
        let mut operations = project_base_operations(request, &slug, manifest)?;
        operations.push(file_operation(
            &format!("{}/service/Cargo.toml", request.path),
            rust_workspace_toml(&slug),
        )?);
        operations.push(file_operation(
            &format!("{}/service/src/lib.rs", request.path),
            "//! Foundation service crate.\n".to_string(),
        )?);
        if clients.iter().any(|client| client == "rust") {
            operations.push(file_operation(
                &format!("{}/clients/rust/Cargo.toml", request.path),
                rust_workspace_manifest_toml(&[format!("crates/{slug}-client")]),
            )?);
            operations.push(file_operation(
                &format!(
                    "{}/clients/rust/crates/{slug}-client/Cargo.toml",
                    request.path
                ),
                rust_workspace_toml(&format!("{slug}-client")),
            )?);
            operations.push(file_operation(
                &format!(
                    "{}/clients/rust/crates/{slug}-client/src/lib.rs",
                    request.path
                ),
                "//! Foundation client crate.\n".to_string(),
            )?);
        }
        if clients.iter().any(|client| client == "typescript") {
            operations.push(file_operation(
                &format!("{}/clients/ts/package.json", request.path),
                package_json(&format!("{slug}-client")),
            )?);
        }
        if clients.iter().any(|client| client == "python") {
            operations.push(file_operation(
                &format!("{}/clients/python/pyproject.toml", request.path),
                pyproject_toml(&format!("{slug}-client")),
            )?);
        }
        Ok(operations)
    }
}

/// Built-in and local filesystem template resolver.
#[derive(Clone, Debug, Default)]
pub struct DefaultTemplateSourceResolver {
    parser: YamlManifestParser,
}

impl TemplateSourceResolver for DefaultTemplateSourceResolver {
    fn resolve(
        &self,
        root: &RepoRoot,
        source: &TemplateSource,
    ) -> Result<ResolvedTemplateSource, RepoctlError> {
        match source {
            TemplateSource::Builtin { name } => {
                let manifest = self.parser.parse_template_bytes(
                    format!("builtin:{name}/template.yaml"),
                    builtin_template_manifest(name)?.as_bytes(),
                )?;
                Ok(ResolvedTemplateSource {
                    root: RepoRelativePath::new(format!("templates/builtin/{name}"))
                        .map_err(RepoctlError::diagnostic)?,
                    manifest,
                })
            }
            TemplateSource::Local {
                root: template_root,
            } => {
                let manifest_path = RepoRelativePath::new(format!("{template_root}/template.yaml"))
                    .map_err(RepoctlError::diagnostic)?;
                let absolute = root.absolute.join(manifest_path.as_str());
                let bytes = fs::read(absolute.as_std_path())
                    .map_err(|source| RepoctlError::io(absolute.clone(), source))?;
                let manifest = self
                    .parser
                    .parse_template_bytes(manifest_path.as_str(), &bytes)?;
                Ok(ResolvedTemplateSource {
                    root: template_root.clone(),
                    manifest,
                })
            }
        }
    }
}

/// MiniJinja-backed template engine.
#[derive(Clone, Debug, Default)]
pub struct MiniJinjaTemplateEngine;

impl MiniJinjaTemplateEngine {
    /// Renders a UTF-8 template string with `MiniJinja`.
    pub fn render_str(
        &self,
        name: &str,
        source: &str,
        context: &serde_json::Value,
    ) -> Result<String, RepoctlError> {
        let mut environment = Environment::new();
        environment
            .add_template_owned(name.to_string(), source.to_string())
            .map_err(|error| {
                RepoctlError::diagnostic(Diagnostic::error(
                    "template.invalid",
                    format!("template `{name}` is invalid: {error}"),
                ))
            })?;
        let template = environment.get_template(name).map_err(|error| {
            RepoctlError::diagnostic(Diagnostic::error(
                "template.invalid",
                format!("template `{name}` is invalid: {error}"),
            ))
        })?;
        template.render(context).map_err(|error| {
            RepoctlError::diagnostic(Diagnostic::error(
                "template.render_failed",
                format!("template `{name}` render failed: {error}"),
            ))
        })
    }

    /// Renders source content according to the template file mode.
    pub fn render_content(
        &self,
        file: &repoctl_core::TemplateFile,
        source_content: &str,
        existing_content: Option<&str>,
        context: &serde_json::Value,
    ) -> Result<String, RepoctlError> {
        match file.mode.as_str() {
            "copy" => Ok(source_content.to_string()),
            "managed" => self.render_str(file.source.as_str(), source_content, context),
            "block" => {
                let rendered = self.render_str(file.source.as_str(), source_content, context)?;
                let block = render_block(&rendered);
                Ok(existing_content.map_or(block.clone(), |current| {
                    replace_or_append_block(current, &block)
                }))
            }
            mode => Err(RepoctlError::diagnostic(Diagnostic::error(
                "template.mode.unsupported",
                format!("unsupported template render mode `{mode}`"),
            ))),
        }
    }
}

impl TemplateEngine for MiniJinjaTemplateEngine {
    fn render(&self, request: &RenderRequest) -> Result<RenderedTemplate, RepoctlError> {
        let rendered = self.render_str("target", &request.file.target, &request.context)?;
        Ok(RenderedTemplate {
            bytes: rendered.into_bytes(),
        })
    }
}

fn root_path(path: &Path) -> Result<Utf8PathBuf, RepoctlError> {
    utf8_path_buf(path.to_path_buf()).map_err(RepoctlError::diagnostic)
}

fn locate_or_current(repo: Option<&Path>) -> Result<Utf8PathBuf, RepoctlError> {
    match repo {
        Some(path) => root_path(path),
        None => std::env::current_dir()
            .map_err(|source| RepoctlError::io(".", source))
            .and_then(|path| utf8_path_buf(path).map_err(RepoctlError::diagnostic)),
    }
}

fn directory_operation(path: &str) -> Result<FileOperation, RepoctlError> {
    Ok(FileOperation {
        path: RepoRelativePath::new(path.to_string()).map_err(RepoctlError::diagnostic)?,
        operation: "directory".to_string(),
        content: None,
    })
}

fn file_operation(path: &str, content: String) -> Result<FileOperation, RepoctlError> {
    Ok(FileOperation {
        path: RepoRelativePath::new(path.to_string()).map_err(RepoctlError::diagnostic)?,
        operation: "managed".to_string(),
        content: Some(content),
    })
}

fn block_operation(path: &str, content: &str) -> Result<FileOperation, RepoctlError> {
    Ok(FileOperation {
        path: RepoRelativePath::new(path.to_string()).map_err(RepoctlError::diagnostic)?,
        operation: "block".to_string(),
        content: Some(render_block(content)),
    })
}

fn apply_operations(
    root: &Utf8PathBuf,
    operations: &[FileOperation],
    dry_run: bool,
) -> Result<Vec<Diagnostic>, RepoctlError> {
    let mut diagnostics = Vec::new();
    if !dry_run {
        fs::create_dir_all(root.as_std_path())
            .map_err(|source| RepoctlError::io(root.clone(), source))?;
    }
    for operation in operations {
        let absolute = root.join(operation.path.as_str());
        if operation.operation == "directory" {
            if !dry_run {
                fs::create_dir_all(absolute.as_std_path())
                    .map_err(|source| RepoctlError::io(absolute.clone(), source))?;
            }
            continue;
        }
        let Some(content) = &operation.content else {
            continue;
        };
        let content_to_write = if absolute.exists() {
            let current = fs::read_to_string(absolute.as_std_path())
                .map_err(|source| RepoctlError::io(absolute.clone(), source))?;
            if current == *content {
                continue;
            }
            if !current.contains(MANAGED_HEADER)
                && !current.contains(BLOCK_BEGIN)
                && operation.operation != "block"
            {
                diagnostics.push(
                    Diagnostic::error(
                        "scaffold.conflict",
                        format!("refusing to overwrite unmanaged file `{}`", operation.path),
                    )
                    .with_path(operation.path.as_str()),
                );
                continue;
            }
            if operation.operation == "block" {
                replace_or_append_block(&current, content)
            } else {
                content.clone()
            }
        } else {
            content.clone()
        };
        if !dry_run {
            if let Some(parent) = absolute.parent() {
                fs::create_dir_all(parent.as_std_path())
                    .map_err(|source| RepoctlError::io(parent.to_path_buf(), source))?;
            }
            fs::write(absolute.as_std_path(), content_to_write)
                .map_err(|source| RepoctlError::io(absolute, source))?;
        }
    }
    if diagnostics
        .iter()
        .any(|diagnostic| diagnostic.severity == repoctl_core::Severity::Error)
    {
        return Err(RepoctlError::Diagnostics { diagnostics });
    }
    Ok(diagnostics)
}

fn skill_operations() -> Result<Vec<FileOperation>, RepoctlError> {
    let mut operations = Vec::new();
    for root in [".claude/skills", ".agent/skills"] {
        operations.push(file_operation(
            &format!("{root}/repoctl/SKILL.md"),
            skill_content(
                "repoctl",
                "Use repoctl commands through the typed facade and keep generated files managed.",
            ),
        )?);
        operations.push(file_operation(
            &format!("{root}/monorepo-boundaries/SKILL.md"),
            skill_content(
                "monorepo-boundaries",
                "Respect app, framework facade, foundation client, proto, and IaC boundaries.",
            ),
        )?);
        operations.push(file_operation(
            &format!("{root}/proto-change/SKILL.md"),
            skill_content(
                "proto-change",
                "Treat source protos under protos/ as owned contracts and never edit generated \
                 code directly.",
            ),
        )?);
    }
    Ok(operations)
}

fn skill_content(name: &str, body: &str) -> String {
    format!("{MANAGED_HEADER}\n# {name}\n\n{body}\n")
}

fn repo_manifest(name: &str) -> String {
    format!(
        r#"{MANAGED_HEADER}
schema: company.repo/v1
name: {name}
layout: functional

defaults:
  owner: "@platform"
  visibility: internal

protos:
  root: protos
  toolchain: buf
  generated_code_policy: consumer-local

ci:
  provider: github-actions
  required_check: repoctl-required
  merge_queue: true

iac:
  core_infra_root: core-infra
  app_iac_mode: colocated
  supported:
    - pulumi
    - terraform
    - opentofu

ai:
  agent_skills_root: .agent/skills
  claude_skills_root: .claude/skills
  context_output: target/repoctl/context-packs

policies:
  cross_app_dependency:
    mode: deny
  framework_internal_dependency:
    mode: deny
  generated_code:
    direct_edit: deny
  prod_change:
    required_owners:
      - "@platform"
      - "@security"
"#
    )
}

fn root_agents(name: &str) -> String {
    format!(
        "{MANAGED_HEADER}\n# {name}\n\nUse repoctl for graph, boundary, scaffold, affected, and \
         task workflows.\n"
    )
}

fn docs_index() -> String {
    format!("{MANAGED_HEADER}\n# Documentation\n\n- Repository initialized by repoctl.\n")
}

fn builtin_template_names() -> [&'static str; 5] {
    ["repo", "app", "framework", "foundation", "skills"]
}

fn builtin_template_manifest(name: &str) -> Result<String, RepoctlError> {
    if !builtin_template_names().contains(&name) {
        return Err(RepoctlError::diagnostic(Diagnostic::error(
            "template.builtin.unknown",
            format!("unknown built-in template `{name}`"),
        )));
    }
    if !name
        .bytes()
        .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_'))
    {
        return Err(RepoctlError::diagnostic(Diagnostic::error(
            "template.name.invalid",
            "built-in template names may only contain ASCII letters, numbers, hyphen, and \
             underscore",
        )));
    }
    Ok(format!(
        r#"schema: repoctl.template/v1
name: {name}
kind: scaffold
engine: minijinja
inputs:
  - name: name
    type: string
    required: true
files:
  - source: README.md.j2
    target: "{{{{ name }}}}/README.md"
    mode: managed
post_render:
  validate:
    - repoctl graph validate
"#
    ))
}

fn builtin_template_file_content(name: &str, source: &str) -> Result<String, RepoctlError> {
    match source {
        "README.md.j2" => Ok(format!(
            "{MANAGED_HEADER}\n# {{{{ name }}}}\n\nGenerated from builtin template `{name}`.\n"
        )),
        "AGENTS.md.j2" => Ok("Use repoctl-managed boundaries for {{ name }}.\n".to_string()),
        _ => Err(RepoctlError::diagnostic(
            Diagnostic::error(
                "template.builtin.source_missing",
                format!("built-in template `{name}` has no source `{source}`"),
            )
            .with_path(source),
        )),
    }
}

fn template_source_content(
    root: &Utf8PathBuf,
    source: &TemplateSource,
    resolved: &ResolvedTemplateSource,
    file: &repoctl_core::TemplateFile,
) -> Result<String, RepoctlError> {
    match source {
        TemplateSource::Builtin { name } => {
            builtin_template_file_content(name, file.source.as_str())
        }
        TemplateSource::Local { .. } => {
            let source_path = resolved
                .root
                .join_project(&file.source)
                .map_err(RepoctlError::diagnostic)?;
            let absolute = root.join(source_path.as_str());
            fs::read_to_string(absolute.as_std_path())
                .map_err(|source| RepoctlError::io(absolute, source))
        }
    }
}

fn should_render(
    expression: Option<&str>,
    context: &serde_json::Value,
    engine: &MiniJinjaTemplateEngine,
) -> Result<bool, RepoctlError> {
    let Some(expression) = expression else {
        return Ok(true);
    };
    let template = format!("{{% if {expression} %}}true{{% else %}}false{{% endif %}}");
    let rendered = engine.render_str("when", &template, context)?;
    Ok(rendered == "true")
}

fn render_block(content: &str) -> String {
    if content.contains(BLOCK_BEGIN) && content.contains(BLOCK_END) {
        content.to_string()
    } else {
        format!("{BLOCK_BEGIN}\n{content}{BLOCK_END}\n")
    }
}

fn replace_or_append_block(current: &str, block: &str) -> String {
    match (current.find(BLOCK_BEGIN), current.find(BLOCK_END)) {
        (Some(begin), Some(end)) if begin <= end => {
            let end_after_marker = end.saturating_add(BLOCK_END.len());
            let prefix = &current[..begin];
            let suffix = &current[end_after_marker..];
            format!("{prefix}{block}{suffix}")
        }
        _ if current.ends_with('\n') => format!("{current}\n{block}"),
        _ => format!("{current}\n\n{block}"),
    }
}

fn project_base_operations(
    request: &NewProjectRequest,
    slug: &str,
    manifest: String,
) -> Result<Vec<FileOperation>, RepoctlError> {
    Ok(vec![
        directory_operation(request.path.as_str())?,
        file_operation(&format!("{}/project.yaml", request.path), manifest)?,
        file_operation(
            &format!("{}/README.md", request.path),
            format!("{MANAGED_HEADER}\n# {slug}\n"),
        )?,
        block_operation(
            &format!("{}/AGENTS.md", request.path),
            &format!("Follow the `{slug}` project boundary and repoctl graph policies.\n"),
        )?,
        file_operation(
            &format!("{}/docs/index.md", request.path),
            format!("{MANAGED_HEADER}\n# {slug} Docs\n"),
        )?,
        file_operation(
            &format!("{}/deploy/README.md", request.path),
            format!("{MANAGED_HEADER}\nDeployment intent lives here.\n"),
        )?,
    ])
}

fn slug_from_path(path: &RepoRelativePath) -> Result<String, RepoctlError> {
    path.as_str()
        .rsplit('/')
        .next()
        .filter(|value| !value.is_empty())
        .map(ToString::to_string)
        .ok_or_else(|| {
            RepoctlError::diagnostic(Diagnostic::error(
                "new.path.invalid",
                "project path must include a final slug",
            ))
        })
}

fn project_name(path: &RepoRelativePath, kind: &ProjectKind) -> Result<String, RepoctlError> {
    let slug = slug_from_path(path)?;
    let prefix = match kind {
        ProjectKind::App => "apps",
        ProjectKind::Framework => "frameworks",
        ProjectKind::FoundationService => "foundations",
        ProjectKind::ProtoRoot | ProjectKind::CoreInfra => {
            return Err(RepoctlError::diagnostic(Diagnostic::error(
                "new.kind.unsupported",
                "unsupported project kind",
            )));
        }
    };
    Ok(format!("{prefix}.{slug}"))
}

fn owner_or_default(owner: Option<&OwnerHandle>, slug: &str) -> String {
    owner.map_or_else(|| format!("@{slug}"), ToString::to_string)
}

fn push_task<'a>(
    tasks: &mut BTreeMap<&'a str, Vec<String>>,
    task: &'a str,
    workspace: &str,
    command: &str,
) {
    tasks.entry(task).or_default().push(format!(
        "    - workspace: {workspace}\n      command: {command}"
    ));
}

fn render_tasks(tasks: &BTreeMap<&str, Vec<String>>) -> String {
    tasks
        .iter()
        .map(|(name, commands)| format!("  {name}:\n{}", commands.join("\n")))
        .collect::<Vec<_>>()
        .join("\n")
}

fn rust_workspace_toml(name: &str) -> String {
    format!(
        r#"{MANAGED_HEADER}
[package]
name = "{name}"
version = "0.1.0"
edition = "2024"

[dependencies]
"#
    )
}

fn rust_workspace_manifest_toml(members: &[String]) -> String {
    let members = members
        .iter()
        .map(|member| format!("    \"{member}\","))
        .collect::<Vec<_>>()
        .join("\n");
    format!(
        r#"{MANAGED_HEADER}
[workspace]
members = [
{members}
]
resolver = "3"
"#
    )
}

fn package_json(name: &str) -> String {
    json!({
        "name": name,
        "version": "0.1.0",
        "private": true,
        "scripts": {
            "check": "tsc --noEmit",
            "build": "tsc --noEmit",
            "test": "bun test"
        }
    })
    .to_string()
}

fn pyproject_toml(name: &str) -> String {
    format!(
        r#"{MANAGED_HEADER}
[project]
name = "{name}"
version = "0.1.0"
requires-python = ">=3.12"
"#
    )
}

fn iac_provider_name(provider: &IacProvider) -> &'static str {
    match provider {
        IacProvider::Pulumi => "pulumi",
        IacProvider::Terraform => "terraform",
        IacProvider::OpenTofu => "opentofu",
    }
}

#[cfg(test)]
mod tests {
    use repoctl_core::{InitProfile, RepoLayout, RepoName};

    use super::*;

    #[test]
    fn test_should_init_functional_repo() {
        let temp = tempfile::tempdir().expect("tempdir");
        let service = ScaffoldService::with_default_adapters();
        let plan = service
            .init(&InitRequest {
                repo_root: temp.path().to_path_buf(),
                name: RepoName::new("acme").expect("name"),
                profile: InitProfile::Startup,
                layout: RepoLayout::Functional,
                dry_run: false,
            })
            .expect("init");
        assert!(
            plan.operations
                .iter()
                .any(|op| op.path.as_str() == "repo.yaml")
        );
        assert!(temp.path().join("apps").is_dir());
        assert!(!temp.path().join("Cargo.toml").exists());
    }

    #[test]
    fn test_should_check_and_sync_skills() {
        let temp = tempfile::tempdir().expect("tempdir");
        let service = ScaffoldService::with_default_adapters();
        let report = service
            .skills(&SkillsFacadeRequest {
                repo: Some(temp.path().to_path_buf()),
                sync: false,
                dry_run: false,
            })
            .expect("check");
        assert!(!report.diagnostics.is_empty());
        let report = service
            .skills(&SkillsFacadeRequest {
                repo: Some(temp.path().to_path_buf()),
                sync: true,
                dry_run: false,
            })
            .expect("sync");
        assert!(report.diagnostics.is_empty());
    }

    #[test]
    fn test_should_new_app_project() {
        let temp = tempfile::tempdir().expect("tempdir");
        let service = ScaffoldService::with_default_adapters();
        service
            .new_project(&NewProjectRequest {
                repo: Some(temp.path().to_path_buf()),
                kind: ProjectKind::App,
                path: RepoRelativePath::new("apps/catalog").expect("path"),
                stack: vec!["rust-api".to_string(), "bun-web".to_string()],
                languages: Vec::new(),
                clients: Vec::new(),
                facade: false,
                iac: Some(IacProvider::Pulumi),
                proto: None,
                owner: None,
                dry_run: false,
            })
            .expect("new app");
        assert!(temp.path().join("apps/catalog/project.yaml").is_file());
        assert!(temp.path().join("apps/catalog/api/Cargo.toml").is_file());
        assert!(temp.path().join("apps/catalog/web/package.json").is_file());
    }

    #[test]
    fn test_should_new_framework_project() {
        let temp = tempfile::tempdir().expect("tempdir");
        let service = ScaffoldService::with_default_adapters();
        service
            .new_project(&NewProjectRequest {
                repo: Some(temp.path().to_path_buf()),
                kind: ProjectKind::Framework,
                path: RepoRelativePath::new("frameworks/runtime").expect("path"),
                stack: Vec::new(),
                languages: vec!["rust".to_string(), "typescript".to_string()],
                clients: Vec::new(),
                facade: true,
                iac: None,
                proto: None,
                owner: None,
                dry_run: false,
            })
            .expect("new framework");
        assert!(
            temp.path()
                .join("frameworks/runtime/project.yaml")
                .is_file()
        );
        assert!(
            temp.path()
                .join("frameworks/runtime/rust/crates/runtime-facade/src/lib.rs")
                .is_file()
        );
        assert!(
            temp.path()
                .join("frameworks/runtime/rust/crates/runtime-facade/Cargo.toml")
                .is_file()
        );
    }

    #[test]
    fn test_should_new_foundation_project() {
        let temp = tempfile::tempdir().expect("tempdir");
        let service = ScaffoldService::with_default_adapters();
        service
            .new_project(&NewProjectRequest {
                repo: Some(temp.path().to_path_buf()),
                kind: ProjectKind::FoundationService,
                path: RepoRelativePath::new("foundations/identity").expect("path"),
                stack: Vec::new(),
                languages: Vec::new(),
                clients: vec![
                    "rust".to_string(),
                    "typescript".to_string(),
                    "python".to_string(),
                ],
                facade: false,
                iac: Some(IacProvider::Pulumi),
                proto: Some(
                    repoctl_core::ProtoPackageName::new("acme.identity.v1").expect("proto"),
                ),
                owner: None,
                dry_run: false,
            })
            .expect("new foundation");
        assert!(
            temp.path()
                .join("foundations/identity/project.yaml")
                .is_file()
        );
        assert!(
            temp.path()
                .join("foundations/identity/clients/python/pyproject.toml")
                .is_file()
        );
        assert!(
            temp.path()
                .join("foundations/identity/clients/rust/crates/identity-client/src/lib.rs")
                .is_file()
        );
    }

    #[test]
    fn test_should_template_render_target() {
        let engine = MiniJinjaTemplateEngine;
        let rendered = engine
            .render(&RenderRequest {
                template: repoctl_core::TemplateManifest {
                    schema: repoctl_core::SchemaId::new("repoctl.template/v1").expect("schema"),
                    name: "test".to_string(),
                    kind: "app".to_string(),
                    engine: "minijinja".to_string(),
                    inputs: Vec::new(),
                    files: Vec::new(),
                    post_render_validate: Vec::new(),
                },
                file: repoctl_core::TemplateFile {
                    source: repoctl_core::ProjectRelativePath::new("files/name.txt").expect("path"),
                    target: "{{ name }}".to_string(),
                    mode: "managed".to_string(),
                    when: None,
                },
                context: serde_json::json!({ "name": "catalog" }),
            })
            .expect("render");
        assert_eq!(rendered.bytes, b"catalog");
    }

    #[test]
    fn test_should_render_block_content_without_overwriting_surrounding_text() {
        let engine = MiniJinjaTemplateEngine;
        let file = repoctl_core::TemplateFile {
            source: repoctl_core::ProjectRelativePath::new("AGENTS.md.j2").expect("path"),
            target: "AGENTS.md".to_string(),
            mode: "block".to_string(),
            when: None,
        };
        let rendered = engine
            .render_content(
                &file,
                "Use {{ name }} boundaries.\n",
                Some("Header\n\n<!-- repoctl:begin -->\nOld\n<!-- repoctl:end -->\nFooter\n"),
                &serde_json::json!({ "name": "catalog" }),
            )
            .expect("render");
        assert!(rendered.contains("Header"));
        assert!(rendered.contains("Use catalog boundaries."));
        assert!(!rendered.contains("Old"));
    }

    #[test]
    fn test_should_resolve_builtin_template_source() {
        let resolver = DefaultTemplateSourceResolver::default();
        let root = RepoRoot {
            absolute: camino::Utf8PathBuf::from("/tmp/repoctl-template-test"),
        };
        let resolved = resolver
            .resolve(
                &root,
                &TemplateSource::Builtin {
                    name: "app".to_string(),
                },
            )
            .expect("resolve");
        assert_eq!(resolved.manifest.schema.as_str(), "repoctl.template/v1");
        assert_eq!(resolved.root.as_str(), "templates/builtin/app");
    }
}
